pipeline {

    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
        }
    }

    environment {
        DOCKER_IMAGE = "nsk7docker/demo-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/NSKiru-thiga77/CICD_java_maven.git'
            }
        }

        stage('Build') {
            steps {
                dir('Java_maven_CICD'){
                sh 'mvn clean compile'
                }   
            }
        }

        stage('Test') {
            steps {
                dir('Java_maven_CICD'){
                sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Java_maven_CICD'){
                sh 'mvn package'
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                dir('Java_maven_CICD'){
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                dir('Java_maven_CICD'){
                sh 'docker build -t $DOCKER_IMAGE:tag123 .'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                dir('Java_maven_CICD'){
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
               
            }
        } 

        stage('Push Docker Image') {
            steps {
                dir('Java_maven_CICD'){
                sh 'docker push $DOCKER_IMAGE:tag123'
                }
            }
        }
    }

    post {

        success {
            emailext (
                subject: "SUCCESS: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} succeeded.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )

 
        }

        failure {
            emailext (
                subject: "FAILURE: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} failed.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )


        }
        
    }
}
